"""
Round-robin tournament runner.

Discovers all valid bot directories (those containing commands.json),
runs every pair head-to-head via engine.py, and prints a standings table
sorted by win-loss record and net chip delta.

Matches run in parallel. Multiple games per matchup reduce variance.

Usage:
    python3 local_tournament.py [--bots dir1 dir2 ...] [--exclude dir1 ...]
                                [--rounds N] [--games N] [--workers N]
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
import shutil
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from itertools import combinations


ROOT = os.path.dirname(os.path.abspath(__file__))
DEFAULT_EXCLUDE = {"player_chatbot"}
ENGINE_PATH = os.path.join(ROOT, "engine.py")
PYTHON = sys.executable

_print_lock = threading.Lock()


def tprint(*args, **kwargs):
    """Thread-safe print."""
    with _print_lock:
        print(*args, **kwargs)


def discover_bots():
    """Return list of (name, path) for every subdirectory with commands.json."""
    bots = []
    for entry in sorted(os.listdir(ROOT)):
        path = os.path.join(ROOT, entry)
        if os.path.isdir(path) and os.path.isfile(os.path.join(path, "commands.json")):
            bots.append((entry, path))
    return bots


def write_temp_config(tmp_dir, p1_name, p1_path, p2_name, p2_path, num_rounds):
    """
    Write config.py and a wrapper script into tmp_dir.

    The wrapper is run as the main script so Python sets sys.path[0] = tmp_dir,
    meaning `from config import *` in engine.py finds our temp config first —
    not ROOT/config.py. This is what makes parallel matches safe.
    """
    results_dir = os.path.join(tmp_dir, "results") + os.sep
    os.makedirs(results_dir, exist_ok=True)

    config = f"""\
# Auto-generated by local_tournament.py
PLAYER_1_NAME = {p1_name!r}
PLAYER_1_PATH = {p1_path!r}
PLAYER_2_NAME = {p2_name!r}
PLAYER_2_PATH = {p2_path!r}
GAME_LOG_FILENAME = "gamelog"
RESULTS_DIR = {results_dir!r}
PLAYER_LOG_SIZE_LIMIT = 524288
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 60.0
BUILD_TIMEOUT = 10.0
CONNECT_TIMEOUT = 10.0
NUM_ROUNDS = {num_rounds}
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1
PLAYER_TIMEOUT = 60
"""
    with open(os.path.join(tmp_dir, "config.py"), "w") as f:
        f.write(config)

    # Wrapper script: lives in tmp_dir so sys.path[0] = tmp_dir when Python runs it.
    # We then append ROOT so engine.py can import everything else it needs.
    wrapper = f"""\
import sys
sys.path.append({ROOT!r})
exec(compile(open({ENGINE_PATH!r}).read(), {ENGINE_PATH!r}, 'exec'))
"""
    with open(os.path.join(tmp_dir, "run.py"), "w") as f:
        f.write(wrapper)

    return results_dir


def parse_final_line(gamelog_path):
    """
    Parse the Final line from gamelog.txt.
    Returns {name: bankroll} dict, or None on failure.
    """
    if not os.path.exists(gamelog_path):
        return None
    with open(gamelog_path) as f:
        content = f.read()
    for line in reversed(content.strip().split("\n")):
        if line.startswith("Final"):
            results = {}
            for m in re.finditer(r",\s*(\S+)\s+\((-?\d+)\)", line):
                results[m.group(1)] = int(m.group(2))
            return results if len(results) == 2 else None
    return None


def run_single_game(p1_name, p1_path, p2_name, p2_path, num_rounds):
    """
    Run one game between two bots. Returns {name: bankroll} or None on failure.
    Each game gets its own temp dir and config — safe to run in parallel.
    """
    tmp_dir = tempfile.mkdtemp(prefix="pkr_")
    try:
        results_dir = write_temp_config(tmp_dir, p1_name, p1_path, p2_name, p2_path, num_rounds)

        proc = subprocess.run(
            [PYTHON, os.path.join(tmp_dir, "run.py")],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=300,
        )

        gamelog = os.path.join(results_dir, "gamelog.txt")
        return parse_final_line(gamelog)

    except subprocess.TimeoutExpired:
        return None
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def run_matchup(p1_name, p1_path, p2_name, p2_path, num_rounds, num_games, label):
    """
    Run num_games games between two bots, return aggregate result dict.
    """
    results = []
    for g in range(1, num_games + 1):
        bankrolls = run_single_game(p1_name, p1_path, p2_name, p2_path, num_rounds)
        if bankrolls is not None:
            results.append(bankrolls)

    if not results:
        tprint(f"  {label} {p1_name} vs {p2_name} ... ALL FAILED")
        return None

    # Aggregate across games
    p1_wins = sum(1 for r in results if r.get(p1_name, 0) > r.get(p2_name, 0))
    p2_wins = sum(1 for r in results if r.get(p2_name, 0) > r.get(p1_name, 0))
    ties    = sum(1 for r in results if r.get(p1_name, 0) == r.get(p2_name, 0))
    p1_avg  = sum(r.get(p1_name, 0) for r in results) / len(results)
    p2_avg  = sum(r.get(p2_name, 0) for r in results) / len(results)

    matchup_winner = p1_name if p1_wins > p2_wins else (p2_name if p2_wins > p1_wins else "TIE")
    tprint(
        f"  {label} {p1_name} vs {p2_name}  →  "
        f"{p1_wins}-{p2_wins}-{ties} (W-L-T)  "
        f"avg chips: {p1_avg:+.0f} / {p2_avg:+.0f}  "
        f"{'← ' + matchup_winner if matchup_winner != 'TIE' else '← TIE'}"
    )

    return {
        p1_name: {"game_wins": p1_wins, "game_losses": p2_wins, "game_ties": ties, "total_chips": sum(r.get(p1_name, 0) for r in results)},
        p2_name: {"game_wins": p2_wins, "game_losses": p1_wins, "game_ties": ties, "total_chips": sum(r.get(p2_name, 0) for r in results)},
    }


def print_standings(standings, num_games):
    rows = []
    for name, s in standings.items():
        w  = s["matchup_wins"]
        l  = s["matchup_losses"]
        t  = s["matchup_ties"]
        gw = s["game_wins"]
        gl = s["game_losses"]
        net = s["total_chips"]
        rows.append((name, w, l, t, gw, gl, net))

    rows.sort(key=lambda r: (-r[1], r[2], -(r[4] - r[5]), -r[6]))

    col_w = max(len(r[0]) for r in rows) + 2
    header = (
        f"{'Bot':<{col_w}} "
        f"{'MW':>4} {'ML':>4} {'MT':>4}  "
        f"{'GW':>5} {'GL':>5}  "
        f"{'Total Chips':>13}"
    )
    note = f"  (MW/ML/MT = matchup wins/losses/ties across {num_games} game(s) each)"
    sep = "-" * len(header)

    print()
    print("=" * len(header))
    print("  STANDINGS")
    print("=" * len(header))
    print(header)
    print(note)
    print(sep)
    for rank, (name, w, l, t, gw, gl, net) in enumerate(rows, 1):
        wl = w - l
        print(
            f"{rank}. {name:<{col_w-3}} "
            f"{w:>4} {l:>4} {t:>4}  "
            f"{gw:>5} {gl:>5}  "
            f"{net:>+13,}"
        )
    print(sep)


def main():
    parser = argparse.ArgumentParser(description="Local round-robin poker tournament")
    parser.add_argument("--bots", nargs="+", default=None,
                        help="Bot directories to include (default: all discovered)")
    parser.add_argument("--exclude", nargs="+", default=list(DEFAULT_EXCLUDE),
                        help=f"Bot directories to exclude (default: {sorted(DEFAULT_EXCLUDE)})")
    parser.add_argument("--rounds", type=int, default=300,
                        help="Hands per game (default: 300)")
    parser.add_argument("--games", type=int, default=3,
                        help="Games per matchup to average over (default: 3)")
    parser.add_argument("--workers", type=int, default=os.cpu_count(),
                        help="Parallel workers (default: cpu count)")
    args = parser.parse_args()

    all_bots = discover_bots()
    exclude = set(args.exclude)

    if args.bots:
        bots = [(n, p) for n, p in all_bots if n in args.bots and n not in exclude]
        missing = set(args.bots) - {n for n, _ in bots} - exclude
        if missing:
            print(f"Warning: bots not found: {missing}")
    else:
        bots = [(n, p) for n, p in all_bots if n not in exclude]

    if len(bots) < 2:
        print("Need at least 2 bots.")
        print("Found:", [n for n, _ in bots])
        sys.exit(1)

    matchups = list(combinations(bots, 2))
    total_games = len(matchups) * args.games

    print(f"\nTournament: {len(bots)} bots, {len(matchups)} matchups, "
          f"{args.games} game(s) each = {total_games} total games, "
          f"{args.rounds} hands/game, {args.workers} parallel workers")
    print("Bots:", ", ".join(n for n, _ in bots))
    print()

    standings = {
        name: {"matchup_wins": 0, "matchup_losses": 0, "matchup_ties": 0,
               "game_wins": 0, "game_losses": 0, "total_chips": 0}
        for name, _ in bots
    }

    futures = {}
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        for i, ((n1, p1), (n2, p2)) in enumerate(matchups, 1):
            label = f"[{i}/{len(matchups)}]"
            future = pool.submit(run_matchup, n1, p1, n2, p2, args.rounds, args.games, label)
            futures[future] = (n1, n2)

        for future in as_completed(futures):
            n1, n2 = futures[future]
            result = future.result()
            if result is None:
                continue

            for name in (n1, n2):
                s = result[name]
                standings[name]["game_wins"]    += s["game_wins"]
                standings[name]["game_losses"]  += s["game_losses"]
                standings[name]["total_chips"]  += s["total_chips"]

            # Matchup winner = whoever won more games in this matchup
            gw1 = result[n1]["game_wins"]
            gw2 = result[n2]["game_wins"]
            if gw1 > gw2:
                standings[n1]["matchup_wins"]   += 1
                standings[n2]["matchup_losses"] += 1
            elif gw2 > gw1:
                standings[n2]["matchup_wins"]   += 1
                standings[n1]["matchup_losses"] += 1
            else:
                standings[n1]["matchup_ties"]   += 1
                standings[n2]["matchup_ties"]   += 1

    print_standings(standings, args.games)


if __name__ == "__main__":
    main()
