"""
Round-robin tournament runner.

Discovers all valid bot directories (those containing commands.json),
runs every pair head-to-head via engine.py, and prints a standings table
sorted by win-loss record and net chip delta.

Usage:
    python3 local_tournament.py [--bots dir1 dir2 ...] [--rounds N]
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
import shutil
from itertools import combinations


ROOT = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(ROOT, "config.py")
ENGINE_PATH = os.path.join(ROOT, "engine.py")
RESULTS_DIR = os.path.join(ROOT, "results")
PYTHON = sys.executable


def discover_bots():
    """Return list of (name, path) for every subdirectory with commands.json."""
    bots = []
    for entry in sorted(os.listdir(ROOT)):
        path = os.path.join(ROOT, entry)
        if os.path.isdir(path) and os.path.isfile(os.path.join(path, "commands.json")):
            bots.append((entry, path))
    return bots


def write_config(p1_name, p1_path, p2_name, p2_path, num_rounds, results_dir):
    config = f"""\
# Auto-generated by local_tournament.py
PLAYER_1_NAME = {p1_name!r}
PLAYER_1_PATH = {p1_path!r}
PLAYER_2_NAME = {p2_name!r}
PLAYER_2_PATH = {p2_path!r}
GAME_LOG_FILENAME = "gamelog"
RESULTS_DIR = {results_dir!r}
PLAYER_LOG_SIZE_LIMIT = 524288
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 60.0
BUILD_TIMEOUT = 10.0
CONNECT_TIMEOUT = 10.0
NUM_ROUNDS = {num_rounds}
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1
PLAYER_TIMEOUT = 60
"""
    with open(CONFIG_PATH, "w") as f:
        f.write(config)


def parse_final_line(gamelog_path):
    """
    Parse the last 'Final' line from gamelog.txt.
    Returns {name: bankroll} dict, or None on failure.
    """
    if not os.path.exists(gamelog_path):
        return None
    with open(gamelog_path) as f:
        content = f.read()
    # "Final, luke_bot (-402), arman (402)"
    match = re.search(r"Final(.*)", content.strip().split("\n")[-1])
    if not match:
        for line in reversed(content.strip().split("\n")):
            if line.startswith("Final"):
                match = re.search(r"Final(.*)", line)
                break
    if not match:
        return None
    results = {}
    for m in re.finditer(r",\s*(\S+)\s+\((-?\d+)\)", match.group(0)):
        results[m.group(1)] = int(m.group(2))
    return results if len(results) == 2 else None


def run_match(p1_name, p1_path, p2_name, p2_path, num_rounds, match_idx, total):
    """Run a single match. Returns (winner_name, loser_name, bankrolls_dict)."""
    # Use a temporary results directory so parallel/sequential runs don't collide
    tmp_results = tempfile.mkdtemp(prefix="pkr_match_")
    try:
        write_config(
            p1_name, p1_path,
            p2_name, p2_path,
            num_rounds,
            tmp_results + os.sep,
        )

        print(f"  [{match_idx}/{total}] {p1_name} vs {p2_name} ... ", end="", flush=True)

        result = subprocess.run(
            [PYTHON, ENGINE_PATH],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=300,
        )

        gamelog = os.path.join(tmp_results, "gamelog.txt")
        bankrolls = parse_final_line(gamelog)

        if bankrolls is None:
            print("FAILED (could not parse result)")
            if result.stdout:
                print("    stdout:", result.stdout[-300:])
            if result.stderr:
                print("    stderr:", result.stderr[-300:])
            return None

        winner = max(bankrolls, key=bankrolls.get)
        loser = min(bankrolls, key=bankrolls.get)
        delta = bankrolls[winner] - bankrolls[loser]
        tied = bankrolls[p1_name] == bankrolls[p2_name]

        if tied:
            print(f"TIE  ({bankrolls[p1_name]:+d} / {bankrolls[p2_name]:+d})")
        else:
            print(f"{winner} wins  ({bankrolls[winner]:+d} vs {bankrolls[loser]:+d}, Δ{delta})")

        return bankrolls

    except subprocess.TimeoutExpired:
        print("TIMEOUT")
        return None
    finally:
        shutil.rmtree(tmp_results, ignore_errors=True)


def print_standings(standings, bots):
    """Print sorted standings table."""
    rows = []
    for name, s in standings.items():
        w, l, t = s["wins"], s["losses"], s["ties"]
        net = s["net_chips"]
        matches = w + l + t
        rows.append((name, w, l, t, matches, net))

    # Sort: wins desc, then losses asc, then net chips desc
    rows.sort(key=lambda r: (-r[1], r[2], -r[5]))

    col_w = max(len(r[0]) for r in rows) + 2
    header = f"{'Bot':<{col_w}} {'W':>4} {'L':>4} {'T':>4} {'W-L':>6} {'Net Chips':>12}"
    sep = "-" * len(header)

    print()
    print("=" * len(header))
    print("  STANDINGS")
    print("=" * len(header))
    print(header)
    print(sep)
    for rank, (name, w, l, t, m, net) in enumerate(rows, 1):
        wl = w - l
        print(f"{rank}. {name:<{col_w-3}} {w:>4} {l:>4} {t:>4} {wl:>+6} {net:>+12,}")
    print(sep)


def main():
    parser = argparse.ArgumentParser(description="Local round-robin poker tournament")
    parser.add_argument(
        "--bots", nargs="+", default=None,
        help="Bot directory names to include (default: all discovered)",
    )
    parser.add_argument(
        "--rounds", type=int, default=300,
        help="Number of hands per match (default: 300)",
    )
    args = parser.parse_args()

    all_bots = discover_bots()

    if args.bots:
        bots = [(n, p) for n, p in all_bots if n in args.bots]
        missing = set(args.bots) - {n for n, _ in bots}
        if missing:
            print(f"Warning: bots not found: {missing}")
    else:
        bots = all_bots

    if len(bots) < 2:
        print("Need at least 2 bots to run a tournament.")
        print("Found:", [n for n, _ in bots])
        sys.exit(1)

    matchups = list(combinations(bots, 2))
    total = len(matchups)

    print(f"\nTournament: {len(bots)} bots, {total} matches, {args.rounds} hands each")
    print("Bots:", ", ".join(n for n, _ in bots))
    print()

    standings = {
        name: {"wins": 0, "losses": 0, "ties": 0, "net_chips": 0}
        for name, _ in bots
    }

    # Save original config to restore after
    with open(CONFIG_PATH) as f:
        original_config = f.read()

    try:
        for i, ((n1, p1), (n2, p2)) in enumerate(matchups, 1):
            bankrolls = run_match(n1, p1, n2, p2, args.rounds, i, total)
            if bankrolls is None:
                continue

            b1, b2 = bankrolls.get(n1, 0), bankrolls.get(n2, 0)
            standings[n1]["net_chips"] += b1
            standings[n2]["net_chips"] += b2

            if b1 > b2:
                standings[n1]["wins"] += 1
                standings[n2]["losses"] += 1
            elif b2 > b1:
                standings[n2]["wins"] += 1
                standings[n1]["losses"] += 1
            else:
                standings[n1]["ties"] += 1
                standings[n2]["ties"] += 1

    finally:
        # Always restore the original config
        with open(CONFIG_PATH, "w") as f:
            f.write(original_config)

    print_standings(standings, bots)


if __name__ == "__main__":
    main()
